
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class updateProducts extends javax.swing.JFrame {
     String  veriableType  ;
     String queryUpdate;
    
    
    
    
    
    
    

    /**
     * Creates new form updateProducts
     */
    public updateProducts() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchBar = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchTable = new javax.swing.JTable();
        buttonUpdate = new javax.swing.JButton();
        vatText = new javax.swing.JTextField();
        nameText = new javax.swing.JTextField();
        barcodText = new javax.swing.JTextField();
        priceText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        numberText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        searchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBarActionPerformed(evt);
            }
        });

        searchButton.setBackground(new java.awt.Color(15, 247, 62));
        searchButton.setText("Search");
        searchButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        searchTable.setAutoCreateRowSorter(true);
        searchTable.setBackground(new java.awt.Color(249, 252, 157));
        searchTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        searchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "Number", "Name", "Price", "Vat", " Barcod"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        searchTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(searchTable);

        buttonUpdate.setBackground(new java.awt.Color(15, 247, 62));
        buttonUpdate.setText("Update");
        buttonUpdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.gray, java.awt.Color.lightGray));
        buttonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateActionPerformed(evt);
            }
        });

        vatText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vatTextActionPerformed(evt);
            }
        });
        vatText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                vatTextKeyTyped(evt);
            }
        });

        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });
        nameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameTextKeyTyped(evt);
            }
        });

        barcodText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barcodTextActionPerformed(evt);
            }
        });
        barcodText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                barcodTextKeyTyped(evt);
            }
        });

        priceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTextActionPerformed(evt);
            }
        });
        priceText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                priceTextKeyTyped(evt);
            }
        });

        jLabel1.setText("barcod");

        jLabel2.setText("number");

        jLabel3.setText("price");

        jLabel4.setText("vat");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Search Number or Name");

        numberText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberTextActionPerformed(evt);
            }
        });
        numberText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numberTextKeyTyped(evt);
            }
        });

        jLabel11.setText("name");

        jButton1.setBackground(new java.awt.Color(118, 186, 253));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numberText, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(290, 290, 290)
                                .addComponent(buttonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(priceText, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(vatText, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(barcodText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(65, 65, 65)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(12, 12, 12)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(2, 2, 2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(barcodText, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(priceText, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(vatText, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(numberText, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(buttonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBarActionPerformed

    
    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        
              
          
                            try {
                                
                searchTable.setModel(Operations.getData(checkValue(), searchTable));
                
                
                   numberText.setText("");
                    nameText.setText("");
                    priceText.setText("");
                   vatText.setText("");
                    barcodText.setText("");
                  searchBar.setText("");      
                numberText.setEnabled(true);
                nameText.setEnabled(true);
                
                
                
                } catch (SQLException ex) {
                
                    Logger.getLogger(addProducts.class.getName()).log(Level.SEVERE, null, ex);
                }
            
                            
        
    }//GEN-LAST:event_searchButtonActionPerformed

     
      public   String checkValue () 
    { 
                      String veriable=  searchBar.getText() ;
                      System.out.print("chech" + veriable );
                        String query;
           

          
        try 
        { 
            // checking valid integer using parseInt() method 
            Integer.parseInt(veriable); 
                    

        query =  "SELECT * FROM tableProduct WHERE number="+veriable;
      queryUpdate = "UPDATE tableProduct SET   number = ?,name = ?,price= ?,vat=?,barcode =? WHERE number="+veriable;   
      veriableType = "Sayı";
                   
        }  
        catch (NumberFormatException e)  
        { 
                        

          query = "SELECT * FROM tableProduct WHERE name="+"'"+veriable+"'";
         queryUpdate ="UPDATE tableProduct SET   number = ?,name = ?,price= ?,vat=?,barcode =? WHERE name="+"'"+veriable+"'";
        veriableType = "Harf";
        Logger.getLogger(addProducts.class.getName()).log(Level.SEVERE, null, e);

        } 
          
       return query;
    } 
     

    
    public class UpdateApp {
String veriable=  searchBar.getText() ;
        
    private Connection connect() {
        // SQLite connection string
        String url = "jdbc:sqlite:database01.db";
        Connection conn = null;
        try {
            conn = DriverManager.getConnection(url);
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        return conn;
    }

 
    public void updateproductName(String number,String name,String price, String vat,String barcod) {
     String sql = queryUpdate;
     
      System.out.println(sql);

        try (Connection conn = this.connect();
                PreparedStatement pstmt = conn.prepareStatement(sql)) {

            // set the corresponding param
            pstmt.setString(1, number);
            pstmt.setString(2, name);
            pstmt.setString(3, price);
            pstmt.setString(4, vat);
            pstmt.setString(5, barcod);

            // update 
            pstmt.executeUpdate();
      JOptionPane.showMessageDialog(null, " Update is Successful!");                
      System.out.println(pstmt);
        } catch (SQLException e) {
            System.out.println(e.getMessage());
                  JOptionPane.showMessageDialog(null, " Update is Unsuccessful, \n"
                          + " please check the product number!");                
        }
              

    }
    public void updateproductNumber(String number,String name,String price, String vat,String barcod) {
        
            String sql = queryUpdate;
     
      System.out.println(sql);
                
                

        try (Connection conn = this.connect();
                PreparedStatement pstmt = conn.prepareStatement(sql)) {

            // set the corresponding param
            pstmt.setString(1, number);
            pstmt.setString(2, name);
            pstmt.setString(3, price);
            pstmt.setString(4, vat);
            pstmt.setString(5, barcod);
            // update 
            pstmt.executeUpdate();
                 JOptionPane.showMessageDialog(null, " Update is Successful!");                

        } catch (SQLException e) {
            System.out.println(e.getMessage());
                 JOptionPane.showMessageDialog(null, " Update is Unsuccessful!");   
        }
    }
       
    
}
    
    
   
   
    
    
    private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed
        // TODO add your handling code here:
       String value1 = numberText.getText(); 
       String value2 = nameText.getText();
       String value3 = priceText.getText();
       String value4 = vatText.getText();
       String value5 = barcodText.getText();
       
      
       UpdateApp  query  =new UpdateApp();
       // update
       
       if (veriableType=="Harf") {
       query.updateproductName(value1,value2,value3,value4,value5);
       }
       else {
              query.updateproductNumber(value1,value2,value3,value4,value5);
       
       }
             
        
        numberText.setText("");
        nameText.setText("");
        priceText.setText("");
       vatText.setText("");
        barcodText.setText("");
    
      nameText.setEnabled(true); 
    numberText.setEnabled(true);
    }//GEN-LAST:event_buttonUpdateActionPerformed

    private void vatTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vatTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vatTextActionPerformed

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextActionPerformed

    private void barcodTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barcodTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barcodTextActionPerformed

    private void priceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTextActionPerformed

    private void searchTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchTableMouseClicked
        
         int index = searchTable.getSelectedRow();

       TableModel model = searchTable.getModel();

       String value1 = (model.getValueAt(index, 1).toString());
       String value2 = (model.getValueAt(index, 2).toString());
       String value3 = (model.getValueAt(index, 3).toString());
       String value4 = (model.getValueAt(index, 4).toString());
       String value5 = (model.getValueAt(index, 5).toString());
       
   
        
     /*  if (veriableType=false) {
       
         numberText.setText(value1);
       nameText.setText(value2);
       priceText.setText(value3);
       vatText.setText(value4);
       barcodText.setText(value5);
        nameText.setEnabled(false); 

       } 
      else  {

           numberText.setText(value1);
       nameText.setText(value2);
       priceText.setText(value3);
       vatText.setText(value4);
       barcodText.setText(value5);

        numberText.setEnabled(false); 
                      System.out.print("çalıştı");  

       
       
       }
       */
      
   System.out.println(veriableType);  
   
    if (veriableType=="Sayı") {
       numberText.setText(value1);
       nameText.setText(value2);
       priceText.setText(value3);
       vatText.setText(value4);
       barcodText.setText(value5);
        numberText.setEnabled(false); 
                      System.out.println("çalıştı Sayı");  
           
           buttonUpdate.setText("Update by Number");

         
        
          }
          if (veriableType=="Harf") {
          System.out.println("ggg"+veriableType);  
         numberText.setText(value1);
       nameText.setText(value2);
       priceText.setText(value3);
       vatText.setText(value4);
       barcodText.setText(value5);
        nameText.setEnabled(false); 
                      System.out.print("çalıştı Harf");  
        
         buttonUpdate.setText("Update by Name");
       }  
        
       
       
       
       

     
// TODO add your handling code here:
    }//GEN-LAST:event_searchTableMouseClicked

    private void numberTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberTextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

         this.toBack();
        setVisible(false);
        new mainJframe().toFront();
        new mainJframe().setState(java.awt.Frame.NORMAL);





        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void priceTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceTextKeyTyped
        // TODO add your handling code here:
        
        
          
        if(     !Character.isDigit(evt.getKeyChar())&&evt.getKeyChar()!='.' && 
                !Character.isDigit(evt.getKeyChar())&&evt.getKeyChar()!=','){
       evt.consume();
                        } 
        else if(evt.getKeyChar()=='.'&&priceText.getText().contains("." )   &&
                evt.getKeyChar()==','&&priceText.getText().contains(",")
                ){
           evt.consume();
            }   

        
                      
        //KURALLAR
        
        if(priceText.getText().length() <0 ||    priceText.getText().length()>=8     ) {  
              
                evt.consume();
              }
        
        
        
    }//GEN-LAST:event_priceTextKeyTyped

    private void vatTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vatTextKeyTyped
        // TODO add your handling code here:
        
         char onlyNumber = evt.getKeyChar();
        if(!(Character.isDigit(onlyNumber))){
            evt.consume();
        }
        
          if(   vatText.getText().length()>=2     ) {  
              
                evt.consume();
              }
        
        
        
        
    }//GEN-LAST:event_vatTextKeyTyped

    private void numberTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numberTextKeyTyped



        
         char onlyNumber = evt.getKeyChar();
        if(!(Character.isDigit(onlyNumber))){
                                                      
 
            evt.consume();
            

              }
                    

        
        else if(numberText.getText().length() <0   || numberText.getText().length() >=5     ) {  
              
                evt.consume();
              }

            
        



        // TODO add your handling code here:
    }//GEN-LAST:event_numberTextKeyTyped

    private void nameTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextKeyTyped
        // TODO add your handling code here:
        
        
        
       
       if(nameText.getText().length() >= 20 ) {  
                evt.consume();

              }
  
      
        
    }//GEN-LAST:event_nameTextKeyTyped

    private void barcodTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_barcodTextKeyTyped

    
 
                 
    if(barcodText.getText().length() <0 ||    barcodText.getText().length()>=13     ) {  
              
                evt.consume();
              }
     
    
  
        
    
    







        // TODO add your handling code here:
    }//GEN-LAST:event_barcodTextKeyTyped

  
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        
        
        
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateProducts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barcodText;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField numberText;
    private javax.swing.JTextField priceText;
    private javax.swing.JTextField searchBar;
    private javax.swing.JButton searchButton;
    private javax.swing.JTable searchTable;
    private javax.swing.JTextField vatText;
    // End of variables declaration//GEN-END:variables
}
